### ISSUE TITLE
Missing cm_dist

### ISSUE THREAD

**Issue by mingodad** [jeffreykegler/kollos#61]
Hello !
When trying to build this project we get this error:
```
perl etc/cp_libmarpa_cm_dist.pl
From file does not exist: libmarpa/cm_dist/marpa_ami.h at etc/cp_libmarpa_cm_dist.pl line 51, <DATA> line 1.
Makefile:23: recipe for target 'code' failed
make: *** [code] Error 2
```
And even after doing a "libmarp/make dists" we do not have any "cm_dist" folder, when making the latest libmarpa we get the "cm_dist" folder but not all "*.table" needed by kollos are generated.
Cheers !

**Comment by mingodad** [comment]
Comparing the "master/libmarpa/Makefile" and "kollos/libmarpa/Makefile" I could see that a missing line is the culprit:
```
tag:
	git tag -a v$(version) -m "Version $(version)"

cm_dist: timestamp/cm_dist.stamp #!!! This line is missing
```
Cheers !

**Comment by jeffreykegler** [comment]
Thanks!  I am currently immersed in a rewrite of the Marpa theory paper, but I will get to this, certainly before the next release.

**Comment by jeffreykegler** [comment]
@mingodad: My apologies for taking so long to update this.  I am closing this without making a change in the repo, because I've filed a new issue about deciding what to do with this repo (archive it, replace the parse engine, etc.).  The new issue contains a link back to this one, and at the time I decide I will go back and make sure that your fix is either rendered moot, or made.
